Code:exception handling
public class Exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
			try
			{
				System.out.println("going to divide by zero");
				int a=20;
				int b =a/0;
			}
			catch(ArithmeticException e)
			{
				System.out.println(e);
			}
			
			try
			{
				int arr[] = new int[4];
				arr[5]=5;
			}
			catch(ArrayIndexOutOfBoundsException e)
			{
				System.out.println(e);
			}
			
			System.out.println("other statement");
		

	}

}


